# Generated by Django 4.1 on 2023-10-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predios',
            name='logo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='upload/'),
        ),
    ]
