# Generated by Django 4.1 on 2023-10-22 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0003_predios_descripcion_predios_email_predios_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predios',
            name='descripcion',
            field=models.CharField(blank=True, db_column='Desripcion', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_nac', models.DateField(db_column='fec_nac', verbose_name='Fecha de nacimiento')),
                ('telef', models.CharField(db_column='telefono', max_length=11, verbose_name='Teléfono')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
    ]
