# Generated by Django 4.1 on 2023-10-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_predios_descripcion_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['user_id'], 'verbose_name': 'Datos de usuario', 'verbose_name_plural': 'Datos de usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
