# Generated by Django 4.1 on 2023-10-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_usuarios_options_alter_usuarios_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='predios',
            name='link_mapa',
            field=models.CharField(blank=True, db_column='link_mapa', max_length=100, null=True),
        ),
    ]
