# Generated by Django 4.1 on 2023-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_predios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predios',
            name='descripcion',
            field=models.CharField(blank=True, db_column='Desripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predios',
            name='link_mapa',
            field=models.CharField(blank=True, db_column='link_mapa', max_length=1000, null=True),
        ),
    ]
