# Generated by Django 4.1 on 2023-10-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_predios_descripcion_alter_predios_link_mapa'),
        ('reservas', '0008_reservas_estado_alter_predios_descripcion_and_more'),
    ]

    operations = [
    ]
