# Generated by Django 4.1 on 2023-10-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_merge_20231030_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='predios',
            name='hora_fin',
            field=models.CharField(blank=True, db_column='hora_fin', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predios',
            name='hora_ini',
            field=models.CharField(blank=True, db_column='hora_ini', max_length=20, null=True),
        ),
    ]
