# Generated by Django 4.1 on 2023-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_predios_hora_fin_predios_hora_ini'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_verificacion',
            field=models.DateField(blank=True, db_column='fecha_verificacion', default=None, null=True, verbose_name='Fecha de verificación'),
        ),
    ]
