# Generated by Django 4.1 on 2023-10-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_predios_hora_fin_predios_hora_ini'),
        ('reservas', '0010_predios_hora_fin_predios_hora_ini'),
    ]

    operations = [
    ]
