# Generated by Django 4.1 on 2023-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_usuarios_fecha_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, db_column='Fecha_Fin', null=True),
        ),
    ]
