# Generated by Django 4.1 on 2023-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_reservas_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canchas',
            name='precio',
            field=models.FloatField(blank=True, db_column='Precio', null=True),
        ),
    ]
