# Generated by Django 4.1 on 2023-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_canchas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canchas',
            name='precio',
            field=models.FloatField(db_column='Precio', default=0),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='precio',
            field=models.FloatField(blank=True, db_column='Precio', null=True),
        ),
    ]
