# Generated by Django 4.1 on 2023-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_alter_canchas_precio_alter_reservas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='anticipo',
            field=models.FloatField(blank=True, db_column='Anticipo', null=True),
        ),
    ]
