# Generated by Django 4.1 on 2023-11-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_reservas_anticipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='anticipo',
            field=models.FloatField(db_column='Anticipo', default=0),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='precio',
            field=models.FloatField(db_column='Precio', default=0),
        ),
    ]
